<?php

const CONST_ROLE_ADMIN = 1;
const CONST_ROLE_USER = 0;
const CONST_ROLE_VENDOR = 2;
const CONST_STATUS_ENABLED = 1;
const CONST_STATUS_DISABLED = 0;

const CONST_DISTRIBUTE_PENDING = 0;
const CONST_DISTRIBUTE_DONE = 1;


const CONST_SETTING_GENERATION = 1;
const CONST_SETTING_POINT_RATE = 2;
const CONST_SETTING_USER_APPLICATION = 3;
const CONST_SETTING_HPA_BONUS = 4;
const CONST_SETTING_STORE_MANAGER_COMMISSION = 5;

const CONST_GENERATION_FIRST = 1;
const CONST_GENERATION_SECOND = 2;
const CONST_GENERATION_THIRD = 3;
const CONST_GENERATION_FOURTH = 4;
const CONST_GENERATION_FIVE = 5;
const CONST_GENERATION_SIX = 6;
const CONST_GENERATION_SEVEN = 7;

const CONST_DISTRIBUTE_DATE = 30;

const CONST_COMMISSION_COMPANY = 20;
const CONST_COMMISSION_GENERATION = 20;
const CONST_COMMISSION_BASIC = 20;

